
name: gc-bench
version: 0.1
author: Andr치s Kov치cs <puttamalac@gmail.com>
maintainer: Andr치s Kov치cs <puttamalac@gmail.com>

dependencies:
- base
- time

ghc-options:
- -O1
- -fworker-wrapper-cbv
- -threaded
- -rtsopts
- '"-with-rtsopts= -N8 -A16M -qb0 -s"'

default-extensions:
- BangPatterns
- BlockArguments
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- Strict

executable:
  main: Main.hs
